### ISSUE TITLE
CMake problem with MQTT examples

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/playground-lingua-franca#103]
In the playground, compiling `examples/C/src/mqtt/MQTTDistributed.lf` now gives the following compile error, which did not occur before.  How to fix this?  Help please.  The error message means nothing to me.

```
CMake Error at paho-extension.cmake:49 (target_link_libraries):
  The keyword signature for target_link_libraries has already been used with
  the target "federate__source".  All uses of target_link_libraries with a
  target must be either all-keyword or all-plain.

  The uses of the keyword signature are here:

   * CMakeLists.txt:85 (target_link_libraries)
   * CMakeLists.txt:87 (target_link_libraries)
   * CMakeLists.txt:97 (target_link_libraries)
```

The offending line in `pho-extension.cmake` is this:

```
target_link_libraries(${LF_MAIN_TARGET} ${PAHO_MQTT_C_LIBRARIES})
```

**Comment by cmnrd** [comment]
The fix is to change the line to:
```
target_link_libraries(${LF_MAIN_TARGET} PRIVATE ${PAHO_MQTT_C_LIBRARIES})
```

This fix works only with versions greater than 0.6.0., so we should wait for the 0.7.0 before we update the example.

**Comment by edwardalee** [comment]
I thought that CI in the playground was running with the latest release, but the MQTT examples fail to build in CI. See https://github.com/lf-lang/playground-lingua-franca/actions/runs/8222781948/job/22484683032
Are we now running the playground CI with the nightly build?

**Comment by cmnrd** [comment]
This appears to be the case, yes. Actually, https://github.com/lf-lang/playground-lingua-franca/pull/101 switched from the release version to LF master (I think because the updated/new examples did not work with the 0.6.0 release).

I don't know how to resolve this. Generally, we should either only merge examples that work with the latest release, or if we want to use master, make sure that all examples are compiled in the LF CI. I just merged https://github.com/lf-lang/playground-lingua-franca/pull/101, which likely will introduce more errors.

It seems like our best bet is releasing 0.7.0 ASAP and then updating the examples quickly.

**Comment by cmnrd** [comment]
I started working on fixes here: https://github.com/lf-lang/playground-lingua-franca/pull/104

I will also push fixes for the syntax updates in https://github.com/lf-lang/lingua-franca/pull/2235 there tomorrow. Feel free to add other fixes as needed.
